# Generated by Django 4.1.7 on 2023-03-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaName', models.CharField(choices=[('Margarita', 'Margarita'), ('Di pollo', 'Di pollo'), ('Rucola', 'Rucola'), ('Bufalina', 'Bufalina'), ('Diavola', 'Diavola')], max_length=100)),
                ('size', models.IntegerField(choices=[(32, '32'), (40, '40')])),
                ('city', models.CharField(max_length=60)),
                ('zipCode', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='email-field')),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
    ]
