# Generated by Django 4.1.7 on 2023-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='zipCode',
            new_name='houseNumber',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pizzaName',
            field=models.CharField(blank=True, choices=[('Margarita', 'Margarita'), ('Di pollo', 'Di pollo'), ('Rucola', 'Rucola'), ('Bufalina', 'Bufalina'), ('Diavola', 'Diavola')], max_length=100, null=True),
        ),
    ]
